apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap-1
  namespace: default
data:
  key1: value1
  key2: value2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap-2
  namespace: default
data:
  keyA: valueA
  keyB: valueB
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secret-1
  namespace: default
type: Opaque
data:
  username: dXNlcjE=  # Base64 encoded value of 'user1'
  password: cGFzc3dvcmQx  # Base64 encoded value of 'password1'
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secret-2
  namespace: default
type: Opaque
data:
  apiKey: YXBpa2V5MQ==  # Base64 encoded value of 'apikey1'
  apiSecret: YXBpc2VjcmV0MQ==  # Base64 encoded value of 'apisecret1'